#udah_nyampe_di_sini_ea__ubah_author_ataupun_ngerecode_semoga_emak_bapaknya_mati_dalam_keadaan_mengenaskan
#buat_yg_nyampe_di_sini_cuman_buat_mempelajari_pemrograman_dan_beberapa_fungsinya_ane_ucapin_selamat_berjuang
#tapi_awaslu_yg_nge_recode_ataupun_mengganti_author
clear
python2 bajwiwo2jeiwi2u4ur839w8e8r8r888888iinekieoowowjwowoe8eieiebabianjing82iwbsiwi829ohwow8wueheodieiejnekieoowowjwowoe8eieiebabianjing82iwbsiwi829ohwow8wueheodieiejdnw9u3ueie8eirjeiei3dnw9u3ueie8eirjeiei3.py
