#!/system/xbin/bash
#hey pemalas? Ubah author gw doain semoga emak bapak lu mati dan lu sial 49 tahun dan lu mandul!!!!!
clear
blue='\e[1;34m'
green='\e[1;32m'
purple='\[1;35m'
cyan='\e[1;36m'
red='\e[1;31m'
white='\e[1;37m'
yellow='\e[1;33m'
echo "\033[1;31m ┏━╮╭━┓ ╭━━━━━━╮  \033[31;1m●▬▬▬▬▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬▬▬▬●
\033[1;91m ┃┏┗┛┓┃╭┫\033[1;92m*ERR0R*\033[1;91m┃   \033[1;34m╔═╗╦ ╦╔═╗╦═╗╔╦╗  \033[1;93m╗  ◉╦╗╦╦╔═
\033[1;91m ╰┓▋▋┏╯╯╰━━━━━━╯    \033[1;34m╚═╗╠═╣║ ║╠╦╝ ║   \033[1;33m║  ╗║║║╠╩╗
\033[1;91m╭━┻╮╲┗━━━━╮╭╮       \033[1;34m══╝╩ ╩╚═╝╩╚═ ╩   \033[1;33m╚═╝╩║╚╝╩ ╩
\033[1;91m┃▎▎┃╲╲╲╲╲╲┣━╯     \033[31;1m«=============๑✧✧๑=============»
\033[1;91m╰━┳┻▅╯╲╲╲╲┃            \033[48;5;0;38;5;197m╦═╗╦═╗╔═╗╔═╗╔═╗╦╗╔╗
\033[1;91m  ╰━┳┓┏┳┓┏╯            \033[48;5;0;38;5;197m╠═╝╠╦╝║ ║║ ╦╠═╣║╚╝║
\033[1;91m    ┗┻┛┗┻┛            \033[48;5;0;38;5;197m ╩  ╩╚═╚═╝╚═╝╩ ╩╩  ╩
\033[1;33m╔╦═══════════════════════════════════════════════╗
╠╝  \033[1;30m✬  \033[48;5;0;38;5;231mAuthor     \033[1;91m:  \033[1;34mERR0R                       \033[1;33m║
╠╗  \033[1;90m✬  Instagram  \033[1;91m:  \033[1;95m@termux_hacking             \033[1;33m║
║║  \033[1;30m✬  \033[48;5;0;38;5;231mTelegram   \033[1;91m:  \033[1;36mt.me/termuxxhacking        \033[1;33m╔╣
║║  \033[1;90m✬  Team       \033[1;91m:  \033[1;32mITALIA \033[1;37mCYBER    \033[1;31mARMY       \033[1;33m╠╣
╚╬══════════════════════════════════════════════╬╝
\033[1;33m╔╬══════════════════════════════════════════════╬╗
\033[1;33m╠╝\033[1;91m● \033[1;92m Use this script / tools wisely             \033[1;33m╚╣
\033[1;33m║   \033[1;92m   Risk is not borne by his author           \033[1;33m║
\033[1;33m╠════════════════════════════════════════════════╝
\033[1;33m╠═══════════════════════════════════════╗
\033[1;33m╠═▶ \033[1;97mENTER THE LINK WANTED IN SHORTENER  \033[1;33m║
\033[1;33m╠═══════════════════════════════════════╝"
trap ctrl_c INT
ctrl_c() {
clear
cmatrix
sleep 3
exit
}
xdg-open https://www.instagram.com/termux_hacking/?hl=it
read -p "╠═▶    :" link1;
echo -e "╚═╗    :\033[1;32mSHORTLINK WORKED, CHECK THE OUTPUT BELOW"
echo -e "  \033[1;33m▼\033[0m"
curl http://tinyurl.com/api-create.php?url=$link1
echo""
xdg-open https://t.me/termuxxhacking
